"""Default date ideas — used as initial seed when the DB is empty.
Edit this list to add/remove/modify default date ideas. Changes only
take effect on a fresh database. After the first run, edits should be
done via the /admin panel."""

# SEED_IDEAS = [
#     {"id": 1,  "title": "Wieczór przy świecach",           "description": "Zgaście światła, zapalcie świece i zjedzcie kolację tylko we dwoje. Bez telefonów, tylko Wy.", "categories": ["dom", "wieczor"]},
#     {"id": 2,  "title": "Maraton ulubionych filmów",       "description": "Wybierzcie po jednym filmie, który zmienił Wasze życie i obejrzyjcie je razem.", "categories": ["dom", "wieczor"]},
#     {"id": 3,  "title": "Piknik w parku",                  "description": "Koszyk, koc, ulubione przekąski i jedno popołudnie tylko dla Was.", "categories": ["poza", "cieplo", "dzien"]},
#     {"id": 4,  "title": "Spacer o wschodzie słońca",       "description": "Wstańcie wcześnie i przywitajcie nowy dzień razem.", "categories": ["poza", "dzien"]},
#     {"id": 5,  "title": "Wycieczka w góry",                "description": "Wybierzcie szczyt i zdobądźcie go we dwoje.", "categories": ["poza", "czas"]},
#     {"id": 6,  "title": "Wspólne gotowanie",               "description": "Wylosujcie przepis z internetu i ugotujcie coś, czego nigdy nie próbowaliście.", "categories": ["dom"]},
#     {"id": 7,  "title": "Wieczór planszówek",              "description": "Wyciągnijcie najlepsze gry planszowe i ścierajcie się aż do północy.", "categories": ["dom", "wieczor"]},
#     {"id": 8,  "title": "Lepienie bałwana",                "description": "Wróćcie do dzieciństwa i ulepcie najlepszego bałwana na osiedlu.", "categories": ["poza", "zima"]},
#     {"id": 9,  "title": "Kolacja w restauracji",           "description": "Wybierzcie miejsce, w którym nigdy nie byliście i zarezerwujcie stolik.", "categories": ["poza", "pieniadze", "wieczor"]},
#     {"id": 10, "title": "Domowe spa",                      "description": "Maseczki, świece, muzyka. Zrelaksujcie się jak w prawdziwym SPA.", "categories": ["dom", "wieczor"]},
#     {"id": 11, "title": "Karaoke do białego rana",         "description": "Mikrofon, ulubione kawałki i niezapomniany wieczór.", "categories": ["dom", "wieczor"]},
#     {"id": 12, "title": "Wycieczka rowerowa",              "description": "Wyznaczcie trasę co najmniej 20 km i ruszajcie.", "categories": ["poza", "cieplo"]},
#     {"id": 13, "title": "Wieczór gier komputerowych",      "description": "Wybierzcie kooperacyjną grę i przejdźcie ją razem.", "categories": ["dom", "wieczor"]},
#     {"id": 14, "title": "Wizyta w muzeum",                 "description": "Odkryjcie coś nowego w lokalnej galerii lub muzeum.", "categories": ["poza", "dzien"]},
#     {"id": 15, "title": "Wspólne pieczenie ciasta",        "description": "Wypiekajcie razem ciasto od podstaw i zjedzcie je w łóżku.", "categories": ["dom"]},
#     {"id": 16, "title": "Jazda na łyżwach",                "description": "Trzymajcie się za ręce na lodowisku.", "categories": ["poza", "zima"]},
#     {"id": 17, "title": "Sesja zdjęciowa",                 "description": "Zostańcie własnymi fotografami i zróbcie sobie pamiątkowe zdjęcia.", "categories": ["dzien", "czas"]},
#     {"id": 18, "title": "Wyjazd do innego miasta",         "description": "Kupcie bilety na jeden dzień do najbliższego ciekawego miasta.", "categories": ["poza", "czas", "pieniadze"]},
#     {"id": 19, "title": "Maraton seriali",                 "description": "Wybierzcie nowy serial i obejrzyjcie pierwsze 3 odcinki za jednym razem.", "categories": ["dom", "wieczor"]},
#     {"id": 20, "title": "Wieczór degustacji wina",         "description": "Kupcie 3 różne wina i zorganizujcie własną degustację.", "categories": ["dom", "wieczor", "pieniadze"]},
#     {"id": 21, "title": "Spacer z gorącą czekoladą",       "description": "Termos, kubki, ciepłe szaliki i mróz.", "categories": ["poza", "zima"]},
#     {"id": 22, "title": "Wieczór pisania listów",          "description": "Napiszcie sobie listy o tym, co najbardziej w sobie kochacie.", "categories": ["dom", "wieczor"]},
#     {"id": 23, "title": "Wizyta w SPA",                    "description": "Zarezerwujcie zabieg dla par i odpocznijcie razem.", "categories": ["poza", "pieniadze"]},
#     {"id": 24, "title": "Wspólny trening",                 "description": "Wybierzcie się razem na trening lub zróbcie go w domu.", "categories": ["dom"]},
#     {"id": 25, "title": "Wycieczka nad jezioro",           "description": "Pakujcie kostiumy i ruszajcie nad wodę.", "categories": ["poza", "cieplo"]},
#     {"id": 26, "title": "Wieczór z poezją",                "description": "Każde z Was przeczyta drugiemu ulubiony wiersz.", "categories": ["dom", "wieczor"]},
#     {"id": 27, "title": "Spacer w lesie",                  "description": "Cisza, drzewa i tylko Wy dwoje.", "categories": ["poza", "dzien"]},
#     {"id": 28, "title": "Wspólne puzzle",                  "description": "Kupcie puzzle 1000 elementów i ułóżcie je razem.", "categories": ["dom", "czas"]},
#     {"id": 29, "title": "Wyjście do kina",                 "description": "Wybierzcie najnowszą premierę i zaopatrzcie się w popcorn.", "categories": ["poza", "wieczor", "pieniadze"]},
#     {"id": 30, "title": "Romantyczna kolacja w domu",      "description": "Ugotujcie 3-daniowe menu i podajcie je przy świecach.", "categories": ["dom", "wieczor"]},
#     {"id": 31, "title": "Sanki w zimowy dzień",            "description": "Znajdźcie najlepszą górkę i zjeżdżajcie aż do wieczora.", "categories": ["poza", "zima", "dzien"]},
#     {"id": 32, "title": "Wycieczka do ZOO",                "description": "Spędźcie cały dzień wśród zwierząt.", "categories": ["poza", "dzien", "pieniadze"]},
#     {"id": 33, "title": "Wieczór wspomnień",               "description": "Wyciągnijcie stare zdjęcia i wspominajcie najlepsze chwile.", "categories": ["dom", "wieczor"]},
#     {"id": 34, "title": "Zabawa na śniegu",                "description": "Bitwa na śnieżki, aniołki na śniegu, śmiech do utraty tchu.", "categories": ["poza", "zima"]},
#     {"id": 35, "title": "Wspólne malowanie",               "description": "Kupcie farby i namalujcie sobie nawzajem portrety.", "categories": ["dom"]},
#     {"id": 36, "title": "Wyjazd do SPA na weekend",        "description": "Zarezerwujcie weekend tylko dla Was.", "categories": ["poza", "czas", "pieniadze"]},
#     {"id": 37, "title": "Wieczór z teledyskami",           "description": "Pokazujcie sobie nawzajem teledyski, które kochaliście jako nastolatki.", "categories": ["dom", "wieczor"]},
#     {"id": 38, "title": "Wspólny lot balonem",             "description": "Wzbijcie się ponad chmury we dwoje.", "categories": ["poza", "cieplo", "pieniadze"]},
#     {"id": 39, "title": "Wieczór tańca",                   "description": "Włączcie muzykę i tańczcie w salonie do późna.", "categories": ["dom", "wieczor"]},
#     {"id": 40, "title": "Wycieczka nad morze",             "description": "Spakujcie się i ruszajcie nad polskie wybrzeże.", "categories": ["poza", "czas"]},
#     {"id": 41, "title": "Warsztaty kulinarne",             "description": "Zapiszcie się razem na warsztaty gotowania.", "categories": ["poza", "pieniadze"]},
#     {"id": 42, "title": "Wieczór z planem przyszłości",    "description": "Spiszcie wspólne marzenia i plany na najbliższe 5 lat.", "categories": ["dom", "wieczor"]},
#     {"id": 43, "title": "Spacer po deszczu",               "description": "Jedna parasolka, dwa serca.", "categories": ["poza", "dzien"]},
#     {"id": 44, "title": "Wycieczka do skansenu",           "description": "Cofnijcie się w czasie i odkryjcie kawałek historii.", "categories": ["poza", "dzien"]},
#     {"id": 45, "title": "Romantyczny rejs",                "description": "Wynajmijcie łódkę i spędźcie godzinę na wodzie.", "categories": ["poza", "cieplo", "pieniadze"]},
#     {"id": 46, "title": "Wieczór na dachu",                "description": "Wejdźcie na dach (lub balkon) i patrzcie na gwiazdy.", "categories": ["poza", "wieczor"]},
#     {"id": 47, "title": "Wspólne czytanie książki",        "description": "Wybierzcie jedną książkę i czytajcie ją sobie na głos.", "categories": ["dom"]},
#     {"id": 48, "title": "Wycieczka kajakiem",              "description": "Spłyńcie razem rzeką w słoneczny dzień.", "categories": ["poza", "cieplo", "dzien"]},
#     {"id": 49, "title": "Wieczór gier słownych",           "description": "Scrabble, kalambury, państwa-miasta. Bawcie się jak dzieci.", "categories": ["dom", "wieczor"]},
#     {"id": 50, "title": "Wyjazd do innego kraju",          "description": "Spontanicznie zarezerwujcie weekend za granicą.", "categories": ["poza", "czas", "pieniadze"]},
#     {"id": 51, "title": "Wycieczka na targ",               "description": "Pójdźcie razem na lokalny targ i kupcie składniki na obiad.", "categories": ["poza", "dzien"]},
#     {"id": 52, "title": "Wieczór z butelką wina",          "description": "Otwórzcie dobre wino i rozmawiajcie o wszystkim.", "categories": ["dom", "wieczor"]},
#     {"id": 53, "title": "Wspólny bieg",                    "description": "Wybierzcie się razem na 5km bieg w terenie.", "categories": ["poza", "cieplo"]},
#     {"id": 54, "title": "Wieczór masażu",                  "description": "Wymasujcie się nawzajem oliwką zapachową.", "categories": ["dom", "wieczor"]},
#     {"id": 55, "title": "Wizyta w aquaparku",              "description": "Spędźcie cały dzień na zjeżdżalniach.", "categories": ["poza", "pieniadze", "dzien"]},
#     {"id": 56, "title": "Spacer po świątecznym jarmarku",  "description": "Grzaniec, światełka i zimowy klimat.", "categories": ["poza", "zima", "wieczor"]},
#     {"id": 57, "title": "Wyjście do escape roomu",         "description": "Wybierzcie najtrudniejszy pokój i uciekajcie razem.", "categories": ["poza", "pieniadze"]},
#     {"id": 58, "title": "Wieczór nostalgii",               "description": "Obejrzyjcie razem film, który oglądaliście na pierwszej randce.", "categories": ["dom", "wieczor"]},
#     {"id": 59, "title": "Wyjazd pod namiot",               "description": "Spakujcie namiot i przenocujcie w lesie.", "categories": ["poza", "cieplo", "czas"]},
#     {"id": 60, "title": "Pieczenie pierogów",              "description": "Lepcie razem pierogi z różnymi farszami.", "categories": ["dom"]},
#     {"id": 61, "title": "Wieczór z domowym kinem",         "description": "Zróbcie sobie prawdziwą salę kinową z popcornem i kocami.", "categories": ["dom", "wieczor"]},
#     {"id": 62, "title": "Wycieczka rowerem nad rzekę",     "description": "Wyznaczcie cel i ruszajcie z lunchem w plecaku.", "categories": ["poza", "cieplo"]},
#     {"id": 63, "title": "Wspólne origami",                 "description": "Zróbcie razem 1000 żurawi szczęścia. Albo chociaż 10.", "categories": ["dom"]},
#     {"id": 64, "title": "Wieczór z kartami Tarota",        "description": "Wyczytajcie sobie nawzajem przyszłość.", "categories": ["dom", "wieczor"]},
#     {"id": 65, "title": "Wycieczka w nieznane",            "description": "Wybierzcie losowy punkt na mapie i tam pojedźcie.", "categories": ["poza", "czas"]},
#     {"id": 66, "title": "Wspólny zakup roślinki",          "description": "Kupcie wspólną roślinę i opiekujcie się nią razem.", "categories": ["poza", "dzien"]},
#     {"id": 67, "title": "Wieczór z grą RPG",               "description": "Rozegrajcie pierwszą sesję RPG dla par.", "categories": ["dom", "wieczor"]},
#     {"id": 68, "title": "Jazda na nartach",                "description": "Wybierzcie najbliższy stok i szusujcie razem.", "categories": ["poza", "zima", "pieniadze"]},
#     {"id": 69, "title": "Wizyta w teatrze",                "description": "Wybierzcie spektakl, na który nigdy nie poszlibyście sami.", "categories": ["poza", "wieczor", "pieniadze"]},
#     {"id": 70, "title": "Wieczór z mapą gwiazd",           "description": "Pobierzcie aplikację i oglądajcie gwiazdozbiory.", "categories": ["poza", "wieczor"]},
#     {"id": 71, "title": "Spacer ze słuchawkami",           "description": "Każde z Was wybiera playlistę dla drugiego.", "categories": ["poza", "dzien"]},
#     {"id": 72, "title": "Wyprawa do sklepu z winylami",    "description": "Kupcie razem płytę i posłuchajcie jej w całości.", "categories": ["poza", "dzien"]},
#     {"id": 73, "title": "Wieczór z aromaterapią",          "description": "Zapalcie kadzidełka, włączcie muzykę relaksacyjną.", "categories": ["dom", "wieczor"]},
#     {"id": 74, "title": "Wyjazd nad ciepłe morze",         "description": "Spontanicznie zarezerwujcie wakacje all inclusive.", "categories": ["poza", "czas", "pieniadze", "cieplo"]},
#     {"id": 75, "title": "Wieczór bez prądu",               "description": "Wyłączcie wszystko poza świecami i rozmawiajcie.", "categories": ["dom", "wieczor"]},
#     {"id": 76, "title": "Wspólne sadzenie kwiatów",        "description": "Załóżcie razem ogródek na balkonie.", "categories": ["dom", "cieplo"]},
#     {"id": 77, "title": "Wycieczka do parku linowego",     "description": "Pokonajcie razem najtrudniejszą trasę.", "categories": ["poza", "cieplo", "pieniadze"]},
#     {"id": 78, "title": "Wieczór z grami z dzieciństwa",   "description": "Chińczyk, monopol, warcaby. Zabawcie się jak kiedyś.", "categories": ["dom", "wieczor"]},
#     {"id": 79, "title": "Wycieczka na grzyby",             "description": "Wybierzcie się razem do lasu z koszykiem.", "categories": ["poza", "czas", "dzien"]},
#     {"id": 80, "title": "Wieczór tworzenia playlisty",     "description": "Stwórzcie wspólną playlistę „nasze piosenki\".", "categories": ["dom", "wieczor"]},
#     {"id": 81, "title": "Wyjście na koncert",              "description": "Wybierzcie się na koncert ulubionego artysty.", "categories": ["poza", "wieczor", "pieniadze"]},
#     {"id": 82, "title": "Wieczór z planszą wizji",         "description": "Wytnijcie zdjęcia z gazet i zróbcie wspólną planszę marzeń.", "categories": ["dom", "wieczor"]},
#     {"id": 83, "title": "Wspólna kąpiel",                  "description": "Wanna, pianka, świece i bąbelki.", "categories": ["dom", "wieczor"]},
#     {"id": 84, "title": "Wycieczka w czasie",              "description": "Odwiedźcie miejsce Waszej pierwszej randki.", "categories": ["poza", "czas"]},
#     {"id": 85, "title": "Wieczór kreatywny",               "description": "Wymyślcie razem własną grę planszową.", "categories": ["dom", "wieczor"]},
#     {"id": 86, "title": "Wycieczka do kawiarni",           "description": "Odwiedźcie kawiarnię, w której nigdy nie byliście.", "categories": ["poza", "dzien"]},
#     {"id": 87, "title": "Spacer nocą po mieście",          "description": "Po północy ulice są tylko Wasze.", "categories": ["poza", "wieczor"]},
#     {"id": 88, "title": "Wycieczka kolejką górską",        "description": "Wsiądźcie na najszybszy rollercoaster.", "categories": ["poza", "pieniadze"]},
#     {"id": 89, "title": "Wspólne warsztaty ceramiczne",    "description": "Ulepcie razem coś na pamiątkę.", "categories": ["poza", "pieniadze"]},
#     {"id": 90, "title": "Wieczór pełen pytań",             "description": "Zadajcie sobie 36 pytań, które prowadzą do miłości.", "categories": ["dom", "wieczor"]},
#     {"id": 91, "title": "Wycieczka do parku rozrywki",     "description": "Cały dzień adrenaliny i śmiechu.", "categories": ["poza", "pieniadze", "dzien"]},
#     {"id": 92, "title": "Wieczór z domową pizzą",          "description": "Zróbcie ciasto, każdy swoją pizzę, urządźcie konkurs.", "categories": ["dom", "wieczor"]},
#     {"id": 93, "title": "Spacer brzegiem rzeki",           "description": "Znajdźcie najpiękniejszy odcinek i przejdźcie go razem.", "categories": ["poza", "cieplo"]},
#     {"id": 94, "title": "Wieczór z fotografią analogową",  "description": "Wywołajcie razem stare zdjęcia.", "categories": ["dom", "wieczor"]},
#     {"id": 95, "title": "Wycieczka do innego województwa", "description": "Zaplanujcie weekendowy wypad za 200 km od domu.", "categories": ["poza", "czas"]},
#     {"id": 96, "title": "Wieczór z domowym koktail-barem", "description": "Każde wymyśla 2 koktajle, robicie blind testing.", "categories": ["dom", "wieczor"]},
#     {"id": 97, "title": "Wspólny remont kąta",             "description": "Wyremontujcie razem jeden kąt mieszkania.", "categories": ["dom", "czas"]},
#     {"id": 98, "title": "Wieczór wymiany prezentów",       "description": "Kupcie sobie nawzajem coś za maksymalnie 20 zł.", "categories": ["dom", "wieczor"]},
#     {"id": 99, "title": "Wycieczka do termalnych basenów", "description": "Spędźcie cały dzień w ciepłej wodzie.", "categories": ["poza", "pieniadze", "zima"]},
#     {"id": 100,"title": "Wieczór ślubowań",                "description": "Spiszcie sobie nowe obietnice na kolejny rok razem.", "categories": ["dom", "wieczor"]},
# ]


SEED_IDEAS = [
    # --- 1. AKTYWNIE I SPORTOWO (15) ---
    {"id": 1, "title": "Gokarty o wszystko", "description": "Ścigamy się na torze. Przegrany przez tydzień zmywa naczynia – albo stawia kolację. Robimy zdjęcie na mecie.", "categories": ["poza", "pieniadze"]},
    {"id": 2, "title": "Wspinaczka na ściance", "description": "Wspinamy się na czas z asekuracją. Kto wyżej, ten wybiera film na wieczór. Na górze czeka obowiązkowe selfie.", "categories": ["poza"]},
    {"id": 3, "title": "Park trampolin", "description": "Godzina skakania, robienia saltek i wygłupów w pianie. Zdjęcie w locie to must-have.", "categories": ["poza"]},
    {"id": 4, "title": "Mecz squasha", "description": "Wypocenie się na korcie, a potem wspólne rozciąganie. Kto pierwszy do 11 punktów?", "categories": ["poza"]},
    {"id": 5, "title": "Jazda na rolkach / łyżwach", "description": "Rolkujemy po mieście albo jedziemy na lodowisko – trzymamy się za ręce, żeby nie upaść.", "categories": ["poza", "zima"]},
    {"id": 6, "title": "Kajaki lub SUP", "description": "Spływ rzeką w słoneczny dzień. Liczy się nie wpadnięcie do wody przy próbie zrobienia zdjęcia.", "categories": ["poza", "cieplo", "dzien"]},
    {"id": 7, "title": "Jazda konna w terenie", "description": "Leśna przejażdżka – nawet jeśli pierwszy raz na koniu, instruktor nas ogarnie. Zdjęcie w siodle obowiązkowe.", "categories": ["poza", "cieplo", "pieniadze"]},
    {"id": 8, "title": "Quady / Terenówka", "description": "Wypożyczamy quada lub auto 4x4 i jedziemy w błoto. Będzie brudno, będzie śmiesznie.", "categories": ["poza", "pieniadze"]},
    {"id": 9, "title": "Bubble Soccer", "description": "Gramy w piłkę w gigantycznych, dmuchanych bąblach. Nikt nie pamięta, kiedy ostatnio tak się śmiał.", "categories": ["poza", "pieniadze"]},
    {"id": 10, "title": "Rowerowa pętla", "description": "Wyznaczamy trasę 20-30 km z przystankiem na lody. Byle nie zapomnieć zapasu wody.", "categories": ["poza", "cieplo", "dzien"]},
    {"id": 11, "title": "Gra w kręgle", "description": "Klasyczny wieczór z kulami – wygrywa ten, kto nie trafi w rynnę. Przegrany stawia pizzę.", "categories": ["poza", "wieczor"]},
    {"id": 12, "title": "Strzelnica (łuk lub paintball)", "description": "Sprawdzamy celność w bezpiecznej rywalizacji. Paintball w lesie – adrenaline gwarantowana.", "categories": ["poza", "pieniadze"]},
    {"id": 13, "title": "Golf miniaturowy", "description": "Mini golf z przeszkodami – więcej śmiechu niż powagi. Robimy fotkę przy windmillu.", "categories": ["poza", "dzien", "cieplo"]},
    {"id": 14, "title": "Bieg z przeszkodami", "description": "Zapisujemy się na lokalny OCR i sprawdzamy, kto lepiej radzi sobie z błotem i linami.", "categories": ["poza", "dzien", "pieniadze"]},
    {"id": 15, "title": "Narciarstwo / Snowboard", "description": "Cały dzień na stoku, a wieczorem grzaniec z pianką. Robimy zdjęcie na szczycie.", "categories": ["poza", "zima", "pieniadze"]},

    # --- 2. KULINARNE WYZWANIA I JEDZENIE (13) ---
    {"id": 16, "title": "Burger od zera", "description": "Sami robimy bułki, mielimy mięso i komponujemy sosy. Kto stworzy lepszego burgera – ocena w ciemno.", "categories": ["dom"]},
    {"id": 17, "title": "Sushi roll’owanie", "description": "Próbujemy zwinąć sushi w domu. Nawet jeśli wyjdą krzywe – będzie smacznie i śmiesznie.", "categories": ["dom"]},
    {"id": 18, "title": "Ostre wyzwanie (Hot Ones)", "description": "Smażymy skrzydełka i testujemy sosy od łagodnego do piekielnego. Kto pierwszy poprosi o mleko?", "categories": ["dom", "wieczor"]},
    {"id": 19, "title": "Kolacja w ciemności", "description": "Jemy w całkowitej ciemności (z zawiązanymi oczami). Zgadujemy, co ląduje na widelcu.", "categories": ["dom", "wieczor"]},
    {"id": 20, "title": "Pieczenie chleba na zakwasie", "description": "Cały dzień wyrastania, a potem zapach świeżego chleba w całym mieszkaniu.", "categories": ["dom", "czas"]},
    {"id": 21, "title": "Degustacja wina / piwa rzemieślniczego", "description": "Kupujemy kilka butelek i robimy własną, ślepą degustację – notujemy oceny.", "categories": ["dom", "wieczor", "pieniadze"]},
    {"id": 22, "title": "Własne lody", "description": "Kręcimy domowe lody lub sorbet z sezonowych owoców. Dekorujemy, robimy fotę, zjadamy.", "categories": ["dom", "cieplo"]},
    {"id": 23, "title": "Wyprawa na food trucki", "description": "Biegamy między food truckami – z każdego bierzemy jedną przekąskę i jemy na pół.", "categories": ["poza", "dzien"]},
    {"id": 24, "title": "Śniadanie do łóżka", "description": "Wstajemy wcześniej i szykujemy wielkie, leniwe śniadanie – jajka, tosty, świeży sok.", "categories": ["dom", "dzien"]},
    {"id": 25, "title": "Domowa pizza na kamieniu", "description": "Rozwałkowujemy ciasto, rzucamy nim w powietrzu (albo próbujemy) i pieczemy na kamieniu.", "categories": ["dom", "wieczor"]},
    {"id": 26, "title": "Kuchnia azjatycka – Wok", "description": "Smażymy na dużym ogniu w woku – makaron, warzywa, sosy. Jedzenie gotowe w 15 minut.", "categories": ["dom"]},
    {"id": 27, "title": "Wyprawa na targ po składniki", "description": "Idziemy na bazar, kupujemy to, co akurat jest sezonowe, i improwizujemy obiad.", "categories": ["poza", "dzien"]},
    {"id": 28, "title": "Picie herbat z całego świata", "description": "Kupujemy zestaw 5 różnych herbat i robimy własną ceremonię parzenia. Z herbatnikami.", "categories": ["dom", "wieczor"]},

    # --- 3. WYPRAWY I PODRÓŻE (12) ---
    {"id": 29, "title": "Rzut rzutką w mapę", "description": "Wieszamy mapę Polski, zamykamy oczy i rzucamy rzutką. Gdzie trafi – tam jedziemy na weekend.", "categories": ["poza", "czas"]},
    {"id": 30, "title": "Miasto – strzał", "description": "Jedziemy do losowego miasta w promieniu 2 godzin. Zero planu – spontaniczność.", "categories": ["poza", "czas"]},
    {"id": 31, "title": "Geocaching", "description": "Gra w poszukiwanie skarbów w terenie. Aplikacja prowadzi nas do ukrytych pudełek.", "categories": ["poza", "dzien"]},
    {"id": 32, "title": "Noc pod namiotem", "description": "Biwak w lesie z ogniskiem, pieczeniem kiełbas i nocą pełną gwiazd.", "categories": ["poza", "czas"]},
    {"id": 33, "title": "Spanie w samochodzie", "description": "Składamy fotele, materac do bagażnika – i śpimy nad jeziorem. Budzik? Wschód słońca.", "categories": ["poza", "wieczor"]},
    {"id": 34, "title": "Zwiedzanie ruin", "description": "Objeżdżamy 3-4 stare zamki lub pałace w okolicy – każdy ma swoją historię.", "categories": ["poza", "czas"]},
    {"id": 35, "title": "Pociągiem w nieznane", "description": "Wsiadamy w pociąg i wysiadamy na pierwszej stacji, która nam się spodoba. Zero planu.", "categories": ["poza", "czas", "pieniadze"]},
    {"id": 36, "title": "Skansen lub muzeum na wolnym powietrzu", "description": "Cofamy się w czasie w muzeum wsi – chaty, narzędzia, zapach starego drewna.", "categories": ["poza", "dzien"]},
    {"id": 37, "title": "Zoo / Farma zwierząt", "description": "Spędzamy dzień ze zwierzakami – karmimy, głaszczemy, robimy selfie z alpaką.", "categories": ["poza", "dzien", "pieniadze"]},
    {"id": 38, "title": "Wyprawa do jaskini", "description": "Zwiedzamy podziemną trasę – kask, latarka, wilgotny klimat. Coś dla odkrywców.", "categories": ["poza"]},
    {"id": 39, "title": "Rejs statkiem", "description": "Kilka godzin na wodzie, może z kolacją. Obserwujemy fale i rozmawiamy o wszystkim.", "categories": ["poza", "pieniadze"]},
    {"id": 40, "title": "Wypad na grzyby", "description": "Wstajemy o świcie, bierzemy koszyki i idziemy do lasu. Potem wspólne smażenie na maśle.", "categories": ["poza", "czas", "dzien"]},

    # --- 4. KULTURA I ROZRYWKA (11) ---
    {"id": 41, "title": "Teatr improwizacji", "description": "Spektakl tworzony na żywo z sugestii publiczności – gwarantowany śmiech do łez.", "categories": ["poza", "wieczor", "pieniadze"]},
    {"id": 42, "title": "Stand-up / Kabaret", "description": "Wieczór w klubie komediowym. Siedzimy z daleka od sceny, żeby nas nie wywołali.", "categories": ["poza", "wieczor", "pieniadze"]},
    {"id": 43, "title": "Kino plenerowe / samochodowe", "description": "Oglądamy film na świeżym powietrzu lub z przedniego siedzenia auta. Koc, popcorn, klimat.", "categories": ["poza", "wieczor"]},
    {"id": 44, "title": "Koncert w małym klubie", "description": "Idziemy na koncert zespołu, którego nie znamy. Może odkryjemy nową muzyczną miłość.", "categories": ["poza", "wieczor"]},
    {"id": 45, "title": "Escape Room", "description": "Zamykamy się w pokoju i mamy 60 minut na ucieczkę. Współpraca albo porażka.", "categories": ["poza", "pieniadze"]},
    {"id": 46, "title": "Karaoke w salce", "description": "Wypożyczamy pokój na kilka godzin i śpiewamy do mikrofonu – nawet jeśli fałszujemy.", "categories": ["poza", "wieczor"]},
    {"id": 47, "title": "Nocne zwiedzanie muzeum", "description": "Muzeum otwarte po zmroku – z latarkami i przewodnikiem. Zupełnie inny wymiar.", "categories": ["poza", "wieczor", "pieniadze"]},
    {"id": 48, "title": "Planetarium", "description": "Leżymy wygodnie pod kopułą pełną gwiazd. Relaks i zachwyt w jednym.", "categories": ["poza", "wieczor"]},
    {"id": 49, "title": "Wystawa interaktywna", "description": "Taka, gdzie wszystko można dotknąć, przekręcić i przetestować.", "categories": ["poza", "dzien"]},
    {"id": 50, "title": "Kino na leżakach", "description": "Seans w kinie z wygodnymi fotelami, cichym serwisem i kocykiem.", "categories": ["poza", "wieczor", "pieniadze"]},
    {"id": 51, "title": "Pokaz tańca / Balet", "description": "Wieczór pełen elegancji i emocji. Podobno faceci też to lubią.", "categories": ["poza", "wieczor", "pieniadze"]},

    # --- 5. NOCNE I KLIMATYCZNE (12) ---
    {"id": 52, "title": "Spacer o 3 nad ranem", "description": "Puste miasto, latarnie, tylko Wy i nocna cisza. Magia, której nie da się zaplanować.", "categories": ["poza", "wieczor"]},
    {"id": 53, "title": "Ognisko na działce", "description": "Palimy ognisko, prażymy ziemniaki, słuchamy muzyki z głośnika.", "categories": ["poza", "wieczor"]},
    {"id": 54, "title": "Nocne kąpanie w jeziorze", "description": "(Tylko w bezpiecznym miejscu!) Kąpiel przy świetle księżyca – odlot.", "categories": ["poza", "cieplo", "wieczor"]},
    {"id": 55, "title": "Patrzenie w gwiazdy z termosem", "description": "Jedziemy za miasto, kładziemy się na karimatach i oglądamy rozgwieżdżone niebo.", "categories": ["poza", "wieczor"]},
    {"id": 56, "title": "Wieczór na dachu", "description": "Wchodzimy na dach (lub balkon) – poduszki, koc, lampki i widok na światła miasta.", "categories": ["poza", "wieczor"]},
    {"id": 57, "title": "Jarmark świąteczny", "description": "Grzaniec, pierniki, światełka i zimowy klimat – spacerujemy, jemy i chłoniemy atmosferę.", "categories": ["poza", "zima", "wieczor"]},
    {"id": 58, "title": "Morsowanie", "description": "Zimą wchodzimy do lodowatej wody. Fotka z sinymi ustami i kciukiem w górę obowiązkowa.", "categories": ["poza", "zima"]},
    {"id": 59, "title": "Nocna sesja w fotobudce", "description": "Robimy serię śmiesznych zdjęć w budce z rekwizytami. Coś na pamiątkę.", "categories": ["poza", "wieczor"]},
    {"id": 60, "title": "Kolacja na podłodze", "description": "Zamiast stołu – materac, świece i poduszki. Kolacja w stylu pikniku w salonie.", "categories": ["dom", "wieczor"]},
    {"id": 61, "title": "Gry w świetle lampki", "description": "Gramy w planszówki lub karty przy jednej lampce – klimat jak w starym detektywistycznym filmie.", "categories": ["dom", "wieczor"]},
    {"id": 62, "title": "Nocny rejs gondolą", "description": "Płyniemy po rzece w mieście, gdy wszystko jest oświetlone. Można udawać Włochów.", "categories": ["poza", "wieczor", "pieniadze"]},
    {"id": 63, "title": "Słuchanie muzyki – test słuchawek", "description": "Każde ma swoje słuchawki, słuchacie tego samego utworu, patrząc sobie w oczy. Cisza, ale razem.", "categories": ["dom", "wieczor"]},

    # --- 6. KREATYWNE I ARTYSTYCZNE (11) ---
    {"id": 64, "title": "Malowanie z zamianą", "description": "Co 5 minut dzwoni budzik – zamieniamy się płótnami i malujemy dalej obraz partnera.", "categories": ["dom"]},
    {"id": 65, "title": "Lepienie z gliny", "description": "Robimy doniczki, miski albo abstrakcyjne rzeźby. Potem suszymy i mamy pamiątkę.", "categories": ["dom"]},
    {"id": 66, "title": "Warsztaty ceramiki", "description": "Idziemy do profesjonalnej pracowni, gdzie instruktor nauczy nas formować na kole.", "categories": ["poza", "pieniadze"]},
    {"id": 67, "title": "Robienie świec zapachowych", "description": "Topimy wosk, dodajemy olejki i tworzymy własne świece. Zysk: zapach i nastrój.", "categories": ["dom"]},
    {"id": 68, "title": "Tworzenie biżuterii", "description": "Robimy dla siebie bransoletki lub pierścionki – z koralików, drutu, skóry.", "categories": ["dom"]},
    {"id": 69, "title": "Projektowanie wymarzonego domu", "description": "Rysujemy na kartce lub w programie nasz wymarzony dom – pokój po pokoju.", "categories": ["dom", "czas"]},
    {"id": 70, "title": "Sesja zdjęciowa (własna)", "description": "Ustawiamy aparat, włączamy lampę i robimy sobie sesję w stylu lat 90. Kto wyjdzie lepiej?", "categories": ["dom"]},
    {"id": 71, "title": "Kręcenie głupiego filmiku", "description": "Nagrywamy wspólny TikToka lub YouTube’a – nawet jeśli nigdy go nie opublikujemy.", "categories": ["dom"]},
    {"id": 72, "title": "Pisanie wiersza / listu", "description": "Każde pisze drugiemu wiersz (może być śmieszny) i odczytuje przy świecach.", "categories": ["dom", "wieczor"]},
    {"id": 73, "title": "Tworzenie własnej gry planszowej", "description": "Wymyślamy zasady, planszę, pionki – i testujemy swoją grę do rana.", "categories": ["dom", "czas"]},
    {"id": 74, "title": "Origami na czas", "description": "Kto złoży więcej żurawi w 10 minut? Papier do boju!", "categories": ["dom"]},

    # --- 7. SPONTANICZNE I SZALONE (9) ---
    {"id": 75, "title": "Randka w ciemno – udajemy obcych", "description": "Ubieramy się elegancko, przychodzimy osobno do baru i udajemy, że się nie znamy.", "categories": ["poza", "wieczor"]},
    {"id": 76, "title": "Stylówki z lumpeksu", "description": "Mamy 15 minut i 30 zł, żeby ubrać drugą osobę. W tych strojach idziemy na kawę.", "categories": ["poza", "dzien"]},
    {"id": 77, "title": "Zamiana ról na cały dzień", "description": "Przez cały dzień mówimy i zachowujemy się jak partner/partnerka. Śmiech co 5 minut.", "categories": ["dom", "dzien"]},
    {"id": 78, "title": "Przebieranka za gwiazdy", "description": "Udajemy znaną parę (np. Beyoncé i Jay-Z) – stroje, sposób bycia, rozmowy.", "categories": ["dom", "wieczor"]},
    {"id": 79, "title": "Autostop w bezpieczne miejsce", "description": "(Tylko dla odważnych) – łapiemy stopa i jedziemy, gdzie nas zawiozą. Przygoda.", "categories": ["poza", "czas"]},
    {"id": 80, "title": "Zwiedzanie salonu najdroższych aut", "description": "Ubieramy się szykownie i udajemy, że chcemy kupić luksusowe auto. Zero wstydu.", "categories": ["poza", "dzien"]},
    {"id": 81, "title": "Fast food na bogato", "description": "Kupujemy żarcie z drive-thru i jemy na parkingu – ze sztućcami, obrusem i świecą w aucie.", "categories": ["poza"]},
    {"id": 82, "title": "Zakupy z zamkniętymi oczami", "description": "Jedno prowadzi drugie po sklepie z zasłoniętymi oczami – wybieramy losowe produkty.", "categories": ["poza"]},
    {"id": 83, "title": "Eksperyment kulinarny – pizza na słodko", "description": "Robimy pizzę z nutellą, truskawkami i bekonem. Albo krewetki z czekoladą. Kto odważy się spróbować?", "categories": ["dom"]},

    # --- 8. DOMOWE ZACISZE I RELAKS (13) ---
    {"id": 84, "title": "Baza z kocy i krzeseł", "description": "Budujemy wielką fortecę z prześcieradeł, kocy i krzeseł. Śpimy w środku i oglądamy filmy.", "categories": ["dom", "wieczor"]},
    {"id": 85, "title": "Skomplikowane LEGO", "description": "Kupujemy duży zestaw i składamy go przez kilka godzin przy drinku.", "categories": ["dom", "czas", "pieniadze"]},
    {"id": 86, "title": "Gry wideo – kooperacja", "description": "Przechodzimy razem grę fabularną – wybieramy klasykę jak 'It Takes Two'.", "categories": ["dom", "wieczor"]},
    {"id": 87, "title": "Puzzle 1000 elementów", "description": "Układamy, słuchając muzyki – rozmawiamy, planujemy, relaksujemy się.", "categories": ["dom", "czas"]},
    {"id": 88, "title": "Maraton filmowy z wyzwaniami", "description": "Oglądamy trylogię i między filmami robimy śmieszne zadania (np. zmiana stroju).", "categories": ["dom", "wieczor"]},
    {"id": 89, "title": "Domowe SPA", "description": "Maseczki, peelingi, kąpiel z solami, świece i relaks. Cały wieczór dla siebie.", "categories": ["dom", "wieczor"]},
    {"id": 90, "title": "Wieczór z książkami", "description": "Każde czyta swoją książkę w tym samym pokoju, przy herbacie i świeczce.", "categories": ["dom", "wieczor"]},
    {"id": 91, "title": "Testowanie kaw z całego świata", "description": "Kupujemy 4 różne ziarna, mielimy, parzymy i oceniamy. Stajemy się baristami.", "categories": ["dom"]},
    {"id": 92, "title": "Domowy koncert – śpiewamy", "description": "Każde śpiewa piosenkę (lub gra na instrumencie) – nawet jeśli to tylko udawanie.", "categories": ["dom", "wieczor"]},
    {"id": 93, "title": "Wieczór bez prądu", "description": "Wyłączamy wszystko poza świecami – rozmawiamy, gramy w karty, słuchamy ciszy.", "categories": ["dom", "wieczor"]},
    {"id": 94, "title": "Kapsuła czasu", "description": "Pakujemy drobne przedmioty i listy do pudełka, które otworzymy za 5 lat.", "categories": ["dom", "wieczor"]},
    {"id": 95, "title": "Wspólne puzzle w 3D", "description": "Składamy model np. kuli ziemskiej lub zamku z papierowych elementów.", "categories": ["dom", "czas"]},
    {"id": 96, "title": "Wieczór gier karcianych", "description": "Gramy w pokera, wojnę lub 'dobble' – stawiamy śmieszne zakłady.", "categories": ["dom", "wieczor"]},

    # --- 9. ZMYSŁOWE I WELLNESS (8) ---
    {"id": 97, "title": "Degustacja czekolady", "description": "Kupujemy 5 różnych czekolad (mleczna, gorzka, z chili) i robimy ślepą degustację.", "categories": ["dom", "wieczor"]},
    {"id": 98, "title": "Wspólny masaż z olejkami", "description": "Uczymy się podstaw masażu – olejki, świece, muzyka. Relaks na najwyższym poziomie.", "categories": ["dom", "wieczor"]},
    {"id": 99, "title": "Floatation – deprywacja sensoryczna", "description": "Leżymy w solance w kabinie – totalna ciemność i cisza. Reset dla mózgu.", "categories": ["poza", "pieniadze"]},
    {"id": 100, "title": "Sauna", "description": "Idziemy do sauny – kilka rund gorąca, potem zimny prysznic, potem relaks.", "categories": ["poza", "pieniadze"]},
    {"id": 101, "title": "Joga we dwoje", "description": "Znajdujemy filmik z partner jogą i próbujemy asan. Śmiech i rozciąganie.", "categories": ["dom"]},
    {"id": 102, "title": "Własne perfumy", "description": "Mieszamy olejki zapachowe i tworzymy 'nasz' zapach. Etykieta z datą.", "categories": ["dom"]},
    {"id": 103, "title": "Aromaterapia – test olejków", "description": "Dobieramy olejki do nastroju (lawenda, pomarańcza, mięta) i tworzymy mikstury.", "categories": ["dom"]},
    {"id": 104, "title": "Relaks z dźwiękami natury", "description": "Zamykamy oczy, słuchamy nagrań deszczu lub lasu – rozmawiamy o tym, co czujemy.", "categories": ["dom", "wieczor"]},

    # --- 10. DLA WSPOMNIEŃ I RELACJI (16) ---
    {"id": 105, "title": "Wieczór z pytaniami", "description": "Zadajemy sobie 36 pytań, które prowadzą do miłości. Głębokie rozmowy gwarantowane.", "categories": ["dom", "wieczor"]},
    {"id": 106, "title": "Przeglądanie starych zdjęć", "description": "Oglądamy zdjęcia z dzieciństwa i opowiadamy sobie historie z przeszłości.", "categories": ["dom", "wieczor"]},
    {"id": 107, "title": "Pisanie listów do siebie", "description": "Piszemy list, który otworzymy za rok. Co chcemy sobie dziś powiedzieć?", "categories": ["dom"]},
    {"id": 108, "title": "Planowanie przyszłości na 5 lat", "description": "Spisujemy 10 rzeczy, które chcemy zrobić razem w ciągu najbliższych 5 lat.", "categories": ["dom", "wieczor"]},
    {"id": 109, "title": "Powrót na pierwszą randkę", "description": "Jedziemy w miejsce, gdzie byliśmy na pierwszej randce. Wspominamy, co wtedy czuliśmy.", "categories": ["poza", "czas"]},
    {"id": 110, "title": "Wspólne ślubowania", "description": "Piszemy sobie nowe obietnice na kolejny rok – mogą być śmieszne i poważne.", "categories": ["dom", "wieczor"]},
    {"id": 111, "title": "Album z Waszymi zdjęciami", "description": "Wybieramy 50 zdjęć i układamy je w album lub wirtualną książkę.", "categories": ["dom", "czas"]},
    {"id": 112, "title": "Wieczór wspomnień", "description": "Każde z Was opowiada o najlepszym momencie ostatniego roku – i o tym, dlaczego był wyjątkowy.", "categories": ["dom", "wieczor"]},
    {"id": 113, "title": "Wspólne słuchanie podcastu", "description": "Znajdujemy ciekawy podcast, słuchamy go i potem dyskutujemy.", "categories": ["dom", "wieczor"]},
    {"id": 114, "title": "Wymiana książek", "description": "Każde wybiera swoją ulubioną książkę i daje ją drugiemu – z dedykacją.", "categories": ["dom"]},
    {"id": 115, "title": "Nauka nowego języka – pierwsze słowa", "description": "Wybieramy język, którego nie znamy, i uczymy się 10 zwrotów. Używamy ich cały dzień.", "categories": ["dom", "dzien"]},
    {"id": 116, "title": "Tworzenie wspólnej playlisty", "description": "Każde dodaje 15 piosenek i tworzycie 'naszą' playlistę na Spotify.", "categories": ["dom", "wieczor"]},
    {"id": 117, "title": "Wybór nowego wspólnego hobby", "description": "Przeglądacie oferty kursów i wybieracie jedno nowe hobby do nauki od zera.", "categories": ["dom"]},
    {"id": 118, "title": "Sadzenie rośliny", "description": "Kupujemy wspólną roślinkę, sadzimy i obiecujemy się nią opiekować.", "categories": ["dom", "dzien"]},
    {"id": 119, "title": "Dzień bez telefonów", "description": "Chowamy telefony na cały dzień – tylko rozmowy, gry, gotowanie, spacer.", "categories": ["dom", "dzien"]},
    {"id": 120, "title": "Pudełko z powodów, dla których Cię kocham", "description": "Każde z Was pisze na karteczkach 10 powodów i wkłada do pudełka. Czytacie w święta.", "categories": ["dom", "wieczor"]},
]

# Frontend category dictionary — keep keys in sync with frontend/src/data/dateIdeas.js
CATEGORIES = {
    "dom":       {"label": "Dom",        "color": "#e85a7d"},
    "poza":      {"label": "Poza domem", "color": "#d94a4a"},
    "dzien":     {"label": "Dzień",      "color": "#f4a261"},
    "wieczor":   {"label": "Wieczór",    "color": "#8e44ad"},
    "cieplo":    {"label": "Ciepło",     "color": "#e76f51"},
    "zima":      {"label": "Zima",       "color": "#5a9bbf"},
    "czas":      {"label": "Czas",       "color": "#9b7653"},
    "pieniadze": {"label": "Pieniądze",  "color": "#2a9d8f"},
}
