"""Default date ideas — used as initial seed when the DB is empty.
Edit this list to add/remove/modify default date ideas. Changes only
take effect on a fresh database. After the first run, edits should be
done via the /admin panel."""

SEED_IDEAS = [
    {"id": 1,  "title": "Wieczór przy świecach",           "description": "Zgaście światła, zapalcie świece i zjedzcie kolację tylko we dwoje. Bez telefonów, tylko Wy.", "categories": ["dom", "wieczor"]},
    {"id": 2,  "title": "Maraton ulubionych filmów",       "description": "Wybierzcie po jednym filmie, który zmienił Wasze życie i obejrzyjcie je razem.", "categories": ["dom", "wieczor"]},
    {"id": 3,  "title": "Piknik w parku",                  "description": "Koszyk, koc, ulubione przekąski i jedno popołudnie tylko dla Was.", "categories": ["poza", "cieplo", "dzien"]},
    {"id": 4,  "title": "Spacer o wschodzie słońca",       "description": "Wstańcie wcześnie i przywitajcie nowy dzień razem.", "categories": ["poza", "dzien"]},
    {"id": 5,  "title": "Wycieczka w góry",                "description": "Wybierzcie szczyt i zdobądźcie go we dwoje.", "categories": ["poza", "czas"]},
    {"id": 6,  "title": "Wspólne gotowanie",               "description": "Wylosujcie przepis z internetu i ugotujcie coś, czego nigdy nie próbowaliście.", "categories": ["dom"]},
    {"id": 7,  "title": "Wieczór planszówek",              "description": "Wyciągnijcie najlepsze gry planszowe i ścierajcie się aż do północy.", "categories": ["dom", "wieczor"]},
    {"id": 8,  "title": "Lepienie bałwana",                "description": "Wróćcie do dzieciństwa i ulepcie najlepszego bałwana na osiedlu.", "categories": ["poza", "zima"]},
    {"id": 9,  "title": "Kolacja w restauracji",           "description": "Wybierzcie miejsce, w którym nigdy nie byliście i zarezerwujcie stolik.", "categories": ["poza", "pieniadze", "wieczor"]},
    {"id": 10, "title": "Domowe spa",                      "description": "Maseczki, świece, muzyka. Zrelaksujcie się jak w prawdziwym SPA.", "categories": ["dom", "wieczor"]},
    {"id": 11, "title": "Karaoke do białego rana",         "description": "Mikrofon, ulubione kawałki i niezapomniany wieczór.", "categories": ["dom", "wieczor"]},
    {"id": 12, "title": "Wycieczka rowerowa",              "description": "Wyznaczcie trasę co najmniej 20 km i ruszajcie.", "categories": ["poza", "cieplo"]},
    {"id": 13, "title": "Wieczór gier komputerowych",      "description": "Wybierzcie kooperacyjną grę i przejdźcie ją razem.", "categories": ["dom", "wieczor"]},
    {"id": 14, "title": "Wizyta w muzeum",                 "description": "Odkryjcie coś nowego w lokalnej galerii lub muzeum.", "categories": ["poza", "dzien"]},
    {"id": 15, "title": "Wspólne pieczenie ciasta",        "description": "Wypiekajcie razem ciasto od podstaw i zjedzcie je w łóżku.", "categories": ["dom"]},
    {"id": 16, "title": "Jazda na łyżwach",                "description": "Trzymajcie się za ręce na lodowisku.", "categories": ["poza", "zima"]},
    {"id": 17, "title": "Sesja zdjęciowa",                 "description": "Zostańcie własnymi fotografami i zróbcie sobie pamiątkowe zdjęcia.", "categories": ["dzien", "czas"]},
    {"id": 18, "title": "Wyjazd do innego miasta",         "description": "Kupcie bilety na jeden dzień do najbliższego ciekawego miasta.", "categories": ["poza", "czas", "pieniadze"]},
    {"id": 19, "title": "Maraton seriali",                 "description": "Wybierzcie nowy serial i obejrzyjcie pierwsze 3 odcinki za jednym razem.", "categories": ["dom", "wieczor"]},
    {"id": 20, "title": "Wieczór degustacji wina",         "description": "Kupcie 3 różne wina i zorganizujcie własną degustację.", "categories": ["dom", "wieczor", "pieniadze"]},
    {"id": 21, "title": "Spacer z gorącą czekoladą",       "description": "Termos, kubki, ciepłe szaliki i mróz.", "categories": ["poza", "zima"]},
    {"id": 22, "title": "Wieczór pisania listów",          "description": "Napiszcie sobie listy o tym, co najbardziej w sobie kochacie.", "categories": ["dom", "wieczor"]},
    {"id": 23, "title": "Wizyta w SPA",                    "description": "Zarezerwujcie zabieg dla par i odpocznijcie razem.", "categories": ["poza", "pieniadze"]},
    {"id": 24, "title": "Wspólny trening",                 "description": "Wybierzcie się razem na trening lub zróbcie go w domu.", "categories": ["dom"]},
    {"id": 25, "title": "Wycieczka nad jezioro",           "description": "Pakujcie kostiumy i ruszajcie nad wodę.", "categories": ["poza", "cieplo"]},
    {"id": 26, "title": "Wieczór z poezją",                "description": "Każde z Was przeczyta drugiemu ulubiony wiersz.", "categories": ["dom", "wieczor"]},
    {"id": 27, "title": "Spacer w lesie",                  "description": "Cisza, drzewa i tylko Wy dwoje.", "categories": ["poza", "dzien"]},
    {"id": 28, "title": "Wspólne puzzle",                  "description": "Kupcie puzzle 1000 elementów i ułóżcie je razem.", "categories": ["dom", "czas"]},
    {"id": 29, "title": "Wyjście do kina",                 "description": "Wybierzcie najnowszą premierę i zaopatrzcie się w popcorn.", "categories": ["poza", "wieczor", "pieniadze"]},
    {"id": 30, "title": "Romantyczna kolacja w domu",      "description": "Ugotujcie 3-daniowe menu i podajcie je przy świecach.", "categories": ["dom", "wieczor"]},
    {"id": 31, "title": "Sanki w zimowy dzień",            "description": "Znajdźcie najlepszą górkę i zjeżdżajcie aż do wieczora.", "categories": ["poza", "zima", "dzien"]},
    {"id": 32, "title": "Wycieczka do ZOO",                "description": "Spędźcie cały dzień wśród zwierząt.", "categories": ["poza", "dzien", "pieniadze"]},
    {"id": 33, "title": "Wieczór wspomnień",               "description": "Wyciągnijcie stare zdjęcia i wspominajcie najlepsze chwile.", "categories": ["dom", "wieczor"]},
    {"id": 34, "title": "Zabawa na śniegu",                "description": "Bitwa na śnieżki, aniołki na śniegu, śmiech do utraty tchu.", "categories": ["poza", "zima"]},
    {"id": 35, "title": "Wspólne malowanie",               "description": "Kupcie farby i namalujcie sobie nawzajem portrety.", "categories": ["dom"]},
    {"id": 36, "title": "Wyjazd do SPA na weekend",        "description": "Zarezerwujcie weekend tylko dla Was.", "categories": ["poza", "czas", "pieniadze"]},
    {"id": 37, "title": "Wieczór z teledyskami",           "description": "Pokazujcie sobie nawzajem teledyski, które kochaliście jako nastolatki.", "categories": ["dom", "wieczor"]},
    {"id": 38, "title": "Wspólny lot balonem",             "description": "Wzbijcie się ponad chmury we dwoje.", "categories": ["poza", "cieplo", "pieniadze"]},
    {"id": 39, "title": "Wieczór tańca",                   "description": "Włączcie muzykę i tańczcie w salonie do późna.", "categories": ["dom", "wieczor"]},
    {"id": 40, "title": "Wycieczka nad morze",             "description": "Spakujcie się i ruszajcie nad polskie wybrzeże.", "categories": ["poza", "czas"]},
    {"id": 41, "title": "Warsztaty kulinarne",             "description": "Zapiszcie się razem na warsztaty gotowania.", "categories": ["poza", "pieniadze"]},
    {"id": 42, "title": "Wieczór z planem przyszłości",    "description": "Spiszcie wspólne marzenia i plany na najbliższe 5 lat.", "categories": ["dom", "wieczor"]},
    {"id": 43, "title": "Spacer po deszczu",               "description": "Jedna parasolka, dwa serca.", "categories": ["poza", "dzien"]},
    {"id": 44, "title": "Wycieczka do skansenu",           "description": "Cofnijcie się w czasie i odkryjcie kawałek historii.", "categories": ["poza", "dzien"]},
    {"id": 45, "title": "Romantyczny rejs",                "description": "Wynajmijcie łódkę i spędźcie godzinę na wodzie.", "categories": ["poza", "cieplo", "pieniadze"]},
    {"id": 46, "title": "Wieczór na dachu",                "description": "Wejdźcie na dach (lub balkon) i patrzcie na gwiazdy.", "categories": ["poza", "wieczor"]},
    {"id": 47, "title": "Wspólne czytanie książki",        "description": "Wybierzcie jedną książkę i czytajcie ją sobie na głos.", "categories": ["dom"]},
    {"id": 48, "title": "Wycieczka kajakiem",              "description": "Spłyńcie razem rzeką w słoneczny dzień.", "categories": ["poza", "cieplo", "dzien"]},
    {"id": 49, "title": "Wieczór gier słownych",           "description": "Scrabble, kalambury, państwa-miasta. Bawcie się jak dzieci.", "categories": ["dom", "wieczor"]},
    {"id": 50, "title": "Wyjazd do innego kraju",          "description": "Spontanicznie zarezerwujcie weekend za granicą.", "categories": ["poza", "czas", "pieniadze"]},
    {"id": 51, "title": "Wycieczka na targ",               "description": "Pójdźcie razem na lokalny targ i kupcie składniki na obiad.", "categories": ["poza", "dzien"]},
    {"id": 52, "title": "Wieczór z butelką wina",          "description": "Otwórzcie dobre wino i rozmawiajcie o wszystkim.", "categories": ["dom", "wieczor"]},
    {"id": 53, "title": "Wspólny bieg",                    "description": "Wybierzcie się razem na 5km bieg w terenie.", "categories": ["poza", "cieplo"]},
    {"id": 54, "title": "Wieczór masażu",                  "description": "Wymasujcie się nawzajem oliwką zapachową.", "categories": ["dom", "wieczor"]},
    {"id": 55, "title": "Wizyta w aquaparku",              "description": "Spędźcie cały dzień na zjeżdżalniach.", "categories": ["poza", "pieniadze", "dzien"]},
    {"id": 56, "title": "Spacer po świątecznym jarmarku",  "description": "Grzaniec, światełka i zimowy klimat.", "categories": ["poza", "zima", "wieczor"]},
    {"id": 57, "title": "Wyjście do escape roomu",         "description": "Wybierzcie najtrudniejszy pokój i uciekajcie razem.", "categories": ["poza", "pieniadze"]},
    {"id": 58, "title": "Wieczór nostalgii",               "description": "Obejrzyjcie razem film, który oglądaliście na pierwszej randce.", "categories": ["dom", "wieczor"]},
    {"id": 59, "title": "Wyjazd pod namiot",               "description": "Spakujcie namiot i przenocujcie w lesie.", "categories": ["poza", "cieplo", "czas"]},
    {"id": 60, "title": "Pieczenie pierogów",              "description": "Lepcie razem pierogi z różnymi farszami.", "categories": ["dom"]},
    {"id": 61, "title": "Wieczór z domowym kinem",         "description": "Zróbcie sobie prawdziwą salę kinową z popcornem i kocami.", "categories": ["dom", "wieczor"]},
    {"id": 62, "title": "Wycieczka rowerem nad rzekę",     "description": "Wyznaczcie cel i ruszajcie z lunchem w plecaku.", "categories": ["poza", "cieplo"]},
    {"id": 63, "title": "Wspólne origami",                 "description": "Zróbcie razem 1000 żurawi szczęścia. Albo chociaż 10.", "categories": ["dom"]},
    {"id": 64, "title": "Wieczór z kartami Tarota",        "description": "Wyczytajcie sobie nawzajem przyszłość.", "categories": ["dom", "wieczor"]},
    {"id": 65, "title": "Wycieczka w nieznane",            "description": "Wybierzcie losowy punkt na mapie i tam pojedźcie.", "categories": ["poza", "czas"]},
    {"id": 66, "title": "Wspólny zakup roślinki",          "description": "Kupcie wspólną roślinę i opiekujcie się nią razem.", "categories": ["poza", "dzien"]},
    {"id": 67, "title": "Wieczór z grą RPG",               "description": "Rozegrajcie pierwszą sesję RPG dla par.", "categories": ["dom", "wieczor"]},
    {"id": 68, "title": "Jazda na nartach",                "description": "Wybierzcie najbliższy stok i szusujcie razem.", "categories": ["poza", "zima", "pieniadze"]},
    {"id": 69, "title": "Wizyta w teatrze",                "description": "Wybierzcie spektakl, na który nigdy nie poszlibyście sami.", "categories": ["poza", "wieczor", "pieniadze"]},
    {"id": 70, "title": "Wieczór z mapą gwiazd",           "description": "Pobierzcie aplikację i oglądajcie gwiazdozbiory.", "categories": ["poza", "wieczor"]},
    {"id": 71, "title": "Spacer ze słuchawkami",           "description": "Każde z Was wybiera playlistę dla drugiego.", "categories": ["poza", "dzien"]},
    {"id": 72, "title": "Wyprawa do sklepu z winylami",    "description": "Kupcie razem płytę i posłuchajcie jej w całości.", "categories": ["poza", "dzien"]},
    {"id": 73, "title": "Wieczór z aromaterapią",          "description": "Zapalcie kadzidełka, włączcie muzykę relaksacyjną.", "categories": ["dom", "wieczor"]},
    {"id": 74, "title": "Wyjazd nad ciepłe morze",         "description": "Spontanicznie zarezerwujcie wakacje all inclusive.", "categories": ["poza", "czas", "pieniadze", "cieplo"]},
    {"id": 75, "title": "Wieczór bez prądu",               "description": "Wyłączcie wszystko poza świecami i rozmawiajcie.", "categories": ["dom", "wieczor"]},
    {"id": 76, "title": "Wspólne sadzenie kwiatów",        "description": "Załóżcie razem ogródek na balkonie.", "categories": ["dom", "cieplo"]},
    {"id": 77, "title": "Wycieczka do parku linowego",     "description": "Pokonajcie razem najtrudniejszą trasę.", "categories": ["poza", "cieplo", "pieniadze"]},
    {"id": 78, "title": "Wieczór z grami z dzieciństwa",   "description": "Chińczyk, monopol, warcaby. Zabawcie się jak kiedyś.", "categories": ["dom", "wieczor"]},
    {"id": 79, "title": "Wycieczka na grzyby",             "description": "Wybierzcie się razem do lasu z koszykiem.", "categories": ["poza", "czas", "dzien"]},
    {"id": 80, "title": "Wieczór tworzenia playlisty",     "description": "Stwórzcie wspólną playlistę „nasze piosenki\".", "categories": ["dom", "wieczor"]},
    {"id": 81, "title": "Wyjście na koncert",              "description": "Wybierzcie się na koncert ulubionego artysty.", "categories": ["poza", "wieczor", "pieniadze"]},
    {"id": 82, "title": "Wieczór z planszą wizji",         "description": "Wytnijcie zdjęcia z gazet i zróbcie wspólną planszę marzeń.", "categories": ["dom", "wieczor"]},
    {"id": 83, "title": "Wspólna kąpiel",                  "description": "Wanna, pianka, świece i bąbelki.", "categories": ["dom", "wieczor"]},
    {"id": 84, "title": "Wycieczka w czasie",              "description": "Odwiedźcie miejsce Waszej pierwszej randki.", "categories": ["poza", "czas"]},
    {"id": 85, "title": "Wieczór kreatywny",               "description": "Wymyślcie razem własną grę planszową.", "categories": ["dom", "wieczor"]},
    {"id": 86, "title": "Wycieczka do kawiarni",           "description": "Odwiedźcie kawiarnię, w której nigdy nie byliście.", "categories": ["poza", "dzien"]},
    {"id": 87, "title": "Spacer nocą po mieście",          "description": "Po północy ulice są tylko Wasze.", "categories": ["poza", "wieczor"]},
    {"id": 88, "title": "Wycieczka kolejką górską",        "description": "Wsiądźcie na najszybszy rollercoaster.", "categories": ["poza", "pieniadze"]},
    {"id": 89, "title": "Wspólne warsztaty ceramiczne",    "description": "Ulepcie razem coś na pamiątkę.", "categories": ["poza", "pieniadze"]},
    {"id": 90, "title": "Wieczór pełen pytań",             "description": "Zadajcie sobie 36 pytań, które prowadzą do miłości.", "categories": ["dom", "wieczor"]},
    {"id": 91, "title": "Wycieczka do parku rozrywki",     "description": "Cały dzień adrenaliny i śmiechu.", "categories": ["poza", "pieniadze", "dzien"]},
    {"id": 92, "title": "Wieczór z domową pizzą",          "description": "Zróbcie ciasto, każdy swoją pizzę, urządźcie konkurs.", "categories": ["dom", "wieczor"]},
    {"id": 93, "title": "Spacer brzegiem rzeki",           "description": "Znajdźcie najpiękniejszy odcinek i przejdźcie go razem.", "categories": ["poza", "cieplo"]},
    {"id": 94, "title": "Wieczór z fotografią analogową",  "description": "Wywołajcie razem stare zdjęcia.", "categories": ["dom", "wieczor"]},
    {"id": 95, "title": "Wycieczka do innego województwa", "description": "Zaplanujcie weekendowy wypad za 200 km od domu.", "categories": ["poza", "czas"]},
    {"id": 96, "title": "Wieczór z domowym koktail-barem", "description": "Każde wymyśla 2 koktajle, robicie blind testing.", "categories": ["dom", "wieczor"]},
    {"id": 97, "title": "Wspólny remont kąta",             "description": "Wyremontujcie razem jeden kąt mieszkania.", "categories": ["dom", "czas"]},
    {"id": 98, "title": "Wieczór wymiany prezentów",       "description": "Kupcie sobie nawzajem coś za maksymalnie 20 zł.", "categories": ["dom", "wieczor"]},
    {"id": 99, "title": "Wycieczka do termalnych basenów", "description": "Spędźcie cały dzień w ciepłej wodzie.", "categories": ["poza", "pieniadze", "zima"]},
    {"id": 100,"title": "Wieczór ślubowań",                "description": "Spiszcie sobie nowe obietnice na kolejny rok razem.", "categories": ["dom", "wieczor"]},
]

# Frontend category dictionary — keep keys in sync with frontend/src/data/dateIdeas.js
CATEGORIES = {
    "dom":       {"label": "Dom",        "color": "#e85a7d"},
    "poza":      {"label": "Poza domem", "color": "#d94a4a"},
    "dzien":     {"label": "Dzień",      "color": "#f4a261"},
    "wieczor":   {"label": "Wieczór",    "color": "#8e44ad"},
    "cieplo":    {"label": "Ciepło",     "color": "#e76f51"},
    "zima":      {"label": "Zima",       "color": "#5a9bbf"},
    "czas":      {"label": "Czas",       "color": "#9b7653"},
    "pieniadze": {"label": "Pieniądze",  "color": "#2a9d8f"},
}
